import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="flex flex-col justify-center items-center h-screen w-full">
      <Head>
        <title>Niobium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="http://localhost:3000">Niobium!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
