import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'

const Home: NextPage = () => {
  const { data: session, status } = useSession()

  if (status === 'loading') {
    return (
      <div className="flex flex-col justify-center items-center h-screen w-full">
        <h1>Loading...</h1>
      </div>
    )
  }

  if (session) {
    console.log(session)
    return (
      <div className="flex flex-col justify-center items-center h-screen w-full">
        Signed is as {session.user?.email} <br />
        <button
          type="button"
          onClick={() => signOut()}
          className="bg-fuchsia-500 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded-full"
        >
          Sign out
        </button>
      </div>
    )
  }

  return (
    <div className="flex flex-col justify-center items-center h-screen w-full">
      Not signed in <br />
      <button
        type="button"
        onClick={() => signIn()}
        className="bg-fuchsia-500 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded-full"
      >
        Sign in
      </button>
    </div>
  )

  // return (
  //   <div className="flex flex-col justify-center items-center h-screen w-full">
  //     <Head>
  //       <title>Niobium</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main>
  //       <h1>
  //         Welcome to <a href="http://localhost:3000">Niobium!</a>
  //       </h1>
  //     </main>
  //   </div>
  // )
}

export default Home
